SMAProject/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('',views.HomePage.as_view(),name='home'),
    path('analysis/',include('analysis.urls',namespace='analysis')),]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name='accounts'

urlpatterns=[
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
]

analysis/urls.py
from django.urls import path,re_path
from . import views

app_name='analysis'

urlpatterns=[
    path('',views.AnalysisView.as_view(),name='analysis_home'),
    path('history/',views.HistoryView.as_view(),name='history'),
    path('results/',views.ResultsView.as_view(),name='results'),
    path('fail/',views.FailView.as_view(),name='fail'),

]

accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.

class User(auth.models.User,auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

analysis/models.py
from django.db import models
from django.contrib.auth import get_user_model
import requests
from django.utils.text import slugify
from django import template,forms


# Create your models here.

register=template.Library()
User=get_user_model()


class Analysis(models.Model):
    user=models.ForeignKey(User,related_name='analysis',on_delete=models.CASCADE)
    topic=models.CharField(('Topic to be searched in Reddit'),max_length=300)
    analysis_positive=models.IntegerField(blank=False, null=False)
    analysis_negative=models.IntegerField(blank=False,null=False)
    analysis_neutral=models.IntegerField(blank=False,null=False)
    created_at=models.DateTimeField(auto_now=True)
    CHOICES2=[('all','all'),('day','day'),('hour','hour'),('month','month'),('week','week'),('year','year')]
    limit = models.IntegerField('Count of "Top Posts" to be searched in Reddit.')
    time_filter=models.CharField('Reddit API time interval',choices=CHOICES2,max_length=300)

    class Meta():
         ordering = ['-created_at']

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):

    class Meta():
        fields=('username','email','password1','password2')
        model=get_user_model()

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label='Display Name'
        self.fields['email'].label="Email Adress"

SMAProject/views.py
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name='index.html'

accounts/views.py
from django.shortcuts import render

# Create your views here.

from django.urls import reverse_lazy
from . import forms
from django.views.generic import CreateView
# Create your views here.

class SignUp(CreateView):
    form_class=forms.UserCreateForm
    success_url=reverse_lazy('login')
    template_name='accounts/signup.html'

analysis/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views import generic
from . import models
from django.shortcuts import get_object_or_404
from django.contrib import messages
import praw
# import nltk
# from nltk.sentiment.vader import SentimentIntensityAnalyzer
from textblob import TextBlob
from praw.models import MoreComments
from django.contrib.auth import get_user_model
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import redirect
from django import template
from prawcore import NotFound



text=' '
register = template.Library()
reddit = praw.Reddit(
     client_id="aAVvsDiycH_NPQ",
     client_secret="rXl4XeCP7aeTCLJInIneoELl_fqNSg",
     user_agent="www.turgutcemyilmazturk.com by /u/tubikcan",
     redirect_uri="https://www.turgutcemyilmazturk.com",


 )


# sia = SentimentIntensityAnalyzer()

# Create your views here.

class AnalysisView(generic.CreateView,LoginRequiredMixin):

    fields=('topic','limit','time_filter')
    model=models.Analysis

    def form_valid(self,form):

            self.object = form.save(commit=False)
            global reddit
            global text
            text=''
            top_posts = reddit.subreddit(self.object.topic).top(self.object.time_filter, limit=self.object.limit)
            try:
                result_dict=AnalysisDone(top_posts)

            except NotFound:
                return HttpResponseRedirect("fail")

            if(result_dict['positive']==0 and result_dict['negative']==0 and result_dict['neutral'] <3):
                return HttpResponseRedirect("fail")

            else:
                # wordCloud(text,self.object.topic,self.request.user.id,str(self.object.created_at))
                self.object.user=self.request.user
                self.object.analysis_neutral=result_dict['neutral']
                self.object.analysis_negative=result_dict['negative']
                self.object.analysis_positive=result_dict['positive']
                self.object.save()
                return HttpResponseRedirect("results")


class FailView(generic.TemplateView,LoginRequiredMixin):
    template_name="analysis/fail.html"


class ResultsView(generic.TemplateView,LoginRequiredMixin):
    template_name="analysis/results.html"
    def get_context_data(self, **kwargs):
        analysis=models.Analysis.objects.filter(user=self.request.user).order_by('-created_at')[0]
        context = super(ResultsView, self).get_context_data(**kwargs)
        context['positive'] = analysis.analysis_positive
        context['negative'] = analysis.analysis_negative
        context['neutral']=analysis.analysis_neutral
        context['topic']=analysis.topic
        return context

class HistoryView(generic.ListView,LoginRequiredMixin):
    context_object_name='h_analysis'
    model=models.Analysis

    def get_queryset(self):
        return models.Analysis.objects.filter(user=self.request.user)


def AnalysisDone(top_posts):
    for submission in top_posts:
        sub_entries_nltk = {'negative': 0, 'positive' : 0, 'neutral' : 0}
        text_blob_sentiment(submission.title, sub_entries_nltk)
        submission_comm = reddit.submission(id=submission.id)

        for count, top_level_comment in enumerate(submission_comm.comments):
            count_comm = 0
            try :
                global text
                text+=top_level_comment.body+','
                text_blob_sentiment(top_level_comment.body, sub_entries_nltk)
                replies_of(top_level_comment,
                           count_comm,
                           sub_entries_nltk)
            except:
                continue

        return sub_entries_nltk


def text_blob_sentiment(review, sub_entries_textblob):
    analysis = TextBlob(review)
    if analysis.sentiment.polarity >= 0.0001:
        if analysis.sentiment.polarity > 0:
            sub_entries_textblob['positive']=sub_entries_textblob['positive']+1
            return 'Positive'
    elif analysis.sentiment.polarity <= -0.0001:
        if analysis.sentiment.polarity <= 0:
            sub_entries_textblob['negative']=sub_entries_textblob['negative'] + 1
            return 'Negative'
    else:
        sub_entries_textblob['neutral']=sub_entries_textblob['neutral'] + 1
        return 'Neutral'


def replies_of(top_level_comment, count_comment, sub_entries_nltk):
    if len(top_level_comment.replies) == 0:
        count_comment = 0
        return
    else:
        for num, comment in enumerate(top_level_comment.replies):
            try:
                count_comment += 1
                text_blob_sentiment(comment.body, sub_entries_nltk)
            except:
                continue
            replies_of(comment, count_comment ,sub_entries_nltk)
#
# def wordCloud(text,topic,user,created_at):
#     wordcloud = WordCloud(width=1280, height=720, margin=0, prefer_horizontal=0.8).generate(text)
#     plt.imshow(wordcloud, interpolation='bilinear')
#     plt.axis("off")
#     #fig=plt.figure()
#     plt.savefig(topic+"_"+str(user)+"_"+created_at+'.png', dpi=200, bbox_inches='tight', pad_inches = 0)
#     #return fig

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
  <div class="container">
    <h1>Login</h1>
    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class='btn btn-default' value="Login">
    </form>
  </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
  <div class="container">
    <h1>Sign Up</h1>
    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class='btn btn-default' value="Sign-Up">
    </form>
  </div>
{% endblock %}

analysis/templates/analysis/analysis.html
{% extends "base.html" %}
{% block content %}
{% endblock %}

analysis/templates/analysis/analysis_form.html
{% extends "analysis/analysis.html" %}
{% load bootstrap3 %}
{% block content %}
<h4>Search a topic!</h4>
  <form  action="{% url 'analysis:analysis_home' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class='btn btn-primary btn-large' value="Search">
  </form>
{% endblock %}

analysis/templates/analysis/analysis_list.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

{% if user.is_authenticated %}
  {% if h_analysis.count > 0 %}

      {% for analysis in h_analysis %}
          <ol class="list-group">

              <li class="list-group-item list-group-item-warning"><b>Search Time:</b> {{analysis.created_at}}</li>
              <li class="list-group-item list-group-item-success"><b>Search Topic:</b> {{analysis.topic}}</li>
              <li class="list-group-item list-group-item-primary"><b>Positive Comments:</b> {{analysis.analysis_positive}}</li>
              <li class="list-group-item list-group-item-danger"><b>Negative Comments:</b> {{analysis.analysis_negative}}</li>
              <li class="list-group-item list-group-item-warning"><b>Neutral Comments:</b> {{analysis.analysis_neutral}}</li>
              
              <br><br><br><br>
          </ol>
      {% endfor %}

  {% else %}
    <div class="container">

            <h3>No search record in your database.</h3>
            <h2>Go to analysis page to do some search</h2>


    </div>

  {% endif %}
{% endif %}
{% endblock %}

analysis/templates/analysis/fail.html
{% extends "analysis/analysis.html" %}


{% block content %}
<div class="container">
  <div class="jumbotron">
    <h3>Your query was invalid , please go back to analysis page and try another query.</h3>
      <h2>There is no such subreddit!</h2>
      <a href="javascript:history.back()" class="btn btn-primary" role="button">Go back!</a>
  </div>
</div>
{% endblock %}

analysis/templates/analysis/history.html
{% extends "base.html" %}
{% block content %}
{% endblock %}

analysis/templates/analysis/results.html
{% extends "analysis/analysis.html" %}


{% block content %}
    <div class="container">

        <h3>Your query was valid , results are saved in your history page.</h3>
        <h2>Here are your results:</h2>
        <ol class="list-group">
          <li class="list-group-item list-group-item-danger"><b>Your search topic is: {{topic}}</b></li>
          <li class="list-group-item list-group-item-primary"><b>There are {{positive}} positive comments</b></li>
          <li class="list-group-item list-group-item-success"><b>There are {{negative}} negative comments</b></li>
          <li class="list-group-item list-group-item-warning"><b>There are {{neutral}} neutral comments</b></li>
        </ol>
      </div>

    <!-- <div id="container" style="width: 75%;">
      <canvas id="results"></canvas>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

  <script>
    var config = {
      type: 'pie',
      data: {
        datasets: [{
          data: {{ data|safe }},
          backgroundColor: [
            '#696969', '#808080', '#A9A9A9', '#C0C0C0', '#D3D3D3'
          ],
          label: 'Population'
        }],
        labels: {{ labels|safe }}
      },
      options: {
        responsive: true
      }
    };

    window.onload = function() {
      var ctx = document.getElementById('pie-chart').getContext('2d');
      window.myPie = new Chart(ctx, config);
    };

  </script> -->
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Social Media Analysis Project</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

   <!-- Latest compiled and minified JavaScript -->
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>

    <link rel="stylesheet" href="{% static 'SMAProject/css/master.css' %}">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-inverse " role='navigation' id='navbar'>
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Home Page</a>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'analysis:analysis_home' %}" class="nav-link">Analysis</a></li>
            <li class="nav-item"><a href="{% url 'analysis:history' %}" class="nav-link">History</a></li>
            <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="nav-link">Log Out</a></li>
          {% else %}
            <li class="nav-item"><a href="{% url 'accounts:login' %}" class="nav-link">Login</a></li>
            <li class="nav-item"><a href="{% url 'accounts:signup' %}" class="nav-link">Sign Up</a></li>
          {% endif %}
        </ul>
      </div>

    </nav>
    <div class="container mycontent">

      {% block content %}
      {% endblock %}

    </div>

  <canvas id="canvas"></canvas>



  </body>
  <script src="{% static "SMAProject/js/master.js"%}" type="text/javascript" ></script>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h1>Welcome to Social Media Analysis Project!</h1>
    {% if user.is_authenticated %}
    <h2>Go to Analysis page to make analysis from Reddit API</h2>
    {% else %}
    <h2>Please login or signup to continue</h2>
    {% endif %}
{% endblock %}